// resources/js/Pages/Dashboard/Blogs/Create.jsx
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.jsx";
import { Head, useForm } from "@inertiajs/react";
import TextInput from "@/Components/TextInput.jsx";
import PrimaryButton from "@/Components/PrimaryButton.jsx";
import { Transition } from "@headlessui/react";
import Form from "@/Components/Form/Form.jsx";
import SecondaryButton from "@/Components/SecondaryButton.jsx";

export default function Index({ auth }) {
    const { data, setData, post, processing, errors, reset } = useForm({
        title: "",
        slug: "",
        meta_title: "",
        meta_description: "",
        meta_tags: "",
        content: "",
    });

    const submit = (e) => {
        e.preventDefault();

        post(route("dashboard.blogs.store"), {
            preserveScroll: true,
            onSuccess: () => {},
        });
    };

    return (
        <AuthenticatedLayout user={auth.user}>
            <Head title="Blog" />
            <div>
                <form onSubmit={submit} className="w-3/4">
                    <Form>
                        <div slot="content">
                            <TextInput
                                id="title"
                                type="title"
                                name="title"
                                value={data.title}
                                className="mt-1 block w-full"
                                isFocused={true}
                                label="Title"
                                onChange={(e) =>
                                    setData("title", e.target.value)
                                }
                            />

                            <TextInput
                                id="slug"
                                type="slug"
                                name="slug"
                                value={data.slug}
                                className="mt-1 block w-full"
                                label="Slug"
                                onChange={(e) =>
                                    setData("slug", e.target.value)
                                }
                            />

                            <TextInput
                                id="meta_title"
                                type="meta_title"
                                name="meta_title"
                                value={data.meta_title}
                                className="mt-1 block w-full"
                                label="Meta Title"
                                onChange={(e) =>
                                    setData("meta_title", e.target.value)
                                }
                            />

                            <TextInput
                                id="meta_description"
                                type="meta_description"
                                name="meta_description"
                                value={data.meta_description}
                                className="mt-1 block w-full"
                                label="Meta Description"
                                onChange={(e) =>
                                    setData("meta_description", e.target.value)
                                }
                            />

                            <TextInput
                                id="meta_tags"
                                type="meta_tags"
                                name="meta_tags"
                                value={data.meta_tags}
                                className="mt-1 block w-full"
                                label="Meta Tags"
                                onChange={(e) =>
                                    setData("meta_tags", e.target.value)
                                }
                            />

                            <TextInput
                                id="content"
                                type="content"
                                name="content"
                                value={data.content}
                                className="mt-1 block w-full"
                                label="Content"
                                onChange={(e) =>
                                    setData("content", e.target.value)
                                }
                            />
                        </div>

                        <div slot="actions">
                            <div className="flex gap-x-2 flex-row-reverse">
                                <PrimaryButton disabled={processing}>
                                    Save
                                </PrimaryButton>

                                <SecondaryButton disabled={processing}>
                                    Save as Draft
                                </SecondaryButton>
                            </div>
                        </div>
                    </Form>
                </form>
            </div>
        </AuthenticatedLayout>
    );
}

// resources/js/Pages/Dashboard/Blogs/Create.vue
<script setup>
import Form from "@/Components/Form/Form.vue";
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.vue";
import { useForm } from "@inertiajs/vue3";
import TextInput from "@/Components/Inputs/TextInput.vue";
import FormElement from "@/Components/Form/FormElement.vue";
import PrimaryButton from "@/Components/Buttons/PrimaryButton.vue";
import TextArea from "@/Components/Inputs/TextArea.vue";
import InputError from "@/Components/Inputs/InputError.vue";
import Checkbox from "@/Components/Inputs/Checkbox.vue";

const form = useForm({
    title: "",
    slug: "",
    meta_title: "",
    meta_description: "",
    meta_tags: "",
    content: "",
    is_draft: false,
});

const submit = () => {
    form.post(route("dashboard.blogs.store"));
};
</script>

<template>
    <AuthenticatedLayout>
        <Form>
            <FormElement>
                <TextInput v-model="form.title" autofocus label="Title" />

                <InputError :message="form.errors.title" />
            </FormElement>

            <FormElement>
                <TextInput v-model="form.slug" label="Slug" />
                <InputError :message="form.errors.slug" />
            </FormElement>

            <FormElement>
                <TextInput v-model="form.meta_title" label="Meta Title" />
                <InputError :message="form.errors.meta_title" />
            </FormElement>

            <FormElement>
                <TextInput
                    v-model="form.meta_description"
                    label="Meta Description"
                />
                <InputError :message="form.errors.meta_description" />
            </FormElement>

            <FormElement>
                <TextInput v-model="form.meta_tags" label="Meta Tags" />
                <InputError :message="form.errors.meta_tags" />
            </FormElement>

            <FormElement>
                <TextArea v-model="form.content" label="Content" />
                <InputError :message="form.errors.content" />
            </FormElement>

            <FormElement>
                <Checkbox
                    v-model="form.is_draft"
                    :checked="form.is_draft"
                    label="Is Draft"
                />
                <InputError :message="form.errors.is_draft" />
            </FormElement>

            <PrimaryButton as="submit" @click.prevent="submit">
                Publish
            </PrimaryButton>
        </Form>
    </AuthenticatedLayout>
</template>
