// resources/js/Pages/Dashboard/Blogs/Index.vue
<script setup>
import { Link, router } from '@inertiajs/vue3'
import Blog from '@/Components/Cards/Blog.vue'
import AuthenticatedLayout from '@/Layouts/AuthenticatedLayout.vue'

defineProps({
    draftBlogs: Array,
    publishedBlogs: Array,
})

const create = () => {
    router.post(route('dashboard.blogs.create'))
}
</script>

<template>
    <AuthenticatedLayout title="Blogs">
        <div class="flex justify-end">
            <Link
                class="bg-primary-500 rounded-xl p-2 text-white font-medium"
                as="button"
                @click="create"
            >
                Create Blog
            </Link>
        </div>

        <div>
            <h1 class="text-2xl">Draft Blogs</h1>
            <div
                v-if="draftBlogs.length"
                class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-y-4 gap-x-4 mt-6"
            >
                <Blog v-for="blog in draftBlogs" :blog="blog" />
            </div>
            <div v-else class="text-gray-400">No blogs in draft status</div>
        </div>

        <div class="mt-8">
            <h1 class="text-2xl">Published Blogs</h1>
            <div
                v-if="publishedBlogs"
                class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-y-4 gap-x-4 mt-6"
            >
                <Blog v-for="blog in publishedBlogs" :blog="blog" />
            </div>
            <div v-else class="text-gray-400">No published blogs</div>
        </div>
    </AuthenticatedLayout>
</template>

// resources/js/Pages/Dashboard/Blogs/Index.jsx
import AuthenticatedLayout from "@/Layouts/AuthenticatedLayout.jsx";
import { Head, Link } from "@inertiajs/react";
import PrimaryLink from "@/Components/Links/PrimaryLink.jsx";

export default function Index({ auth, blogs }) {
    return (
        <AuthenticatedLayout user={auth.user}>
            <Head title="Blog" />

            <PrimaryLink href={route("dashboard.blogs.create")}>
                Create
            </PrimaryLink>

            <div className="grid grid-cols-4">
                {blogs.map((blog, index) => (
                    <div key={index} className="bg-gray-200 p-8 rounded-xl">
                        {blog.title}
                        <br />
                        {blog.author.name}

                        <br />
                        <br />
                        {blog.content}
                    </div>
                ))}
            </div>
        </AuthenticatedLayout>
    );
}
