// resources/js/Components/TextInput.jsx
import { forwardRef, useEffect, useRef } from "react";
import InputLabel from "@/Components/InputLabel.jsx";

export default forwardRef(function TextInput(
    { type = "text", label = "", className = "", isFocused = false, ...props },
    ref,
) {
    const input = ref ? ref : useRef();

    useEffect(() => {
        if (isFocused) {
            input.current.focus();
        }
    }, []);

    return (
        <div>
            <InputLabel className="mb-2" value={label} />

            <input
                {...props}
                type={type}
                className={
                    "border border-gray-300 p-2 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm " +
                    className
                }
                ref={input}
            />
        </div>
    );
});

// resources/js/Components/Inputs/TextInput.vue
<script setup>
import { onMounted, ref } from 'vue'
import InputLabel from '@/Components/Inputs/InputLabel.vue'

defineProps({
    label: {
        type: String,
        default: '',
    },
    type: {
        type: String,
        default: 'text',
    },
})

const model = defineModel({
    type: [String, Number],
    required: true,
})

const input = ref(null)

onMounted(() => {
    if (input.value.hasAttribute('autofocus')) {
        input.value.focus()
    }
})

defineExpose({ focus: () => input.value.focus() })
</script>

<template>
    <div>
        <InputLabel :value="label" />

        <input
            :type="type"
            class="w-full !border-gray-300 focus:border-indigo-500 focus:ring-indigo-500 rounded-md shadow-sm"
            v-model="model"
            ref="input"
        />
    </div>
</template>
